version: "3"

services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.11.8-management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq
    networks:
      - app_network
    restart: always

  producer:
    container_name: producer_app
    build: "producer/"
    ports:
      - "8080:80"
    environment:
      - QUEUENAME=demoq
    networks:
      - app_network
    depends_on:
      - rabbitmq
    volumes:
      - ./persistent-data:/code/app/data  # PERSISTENCIA DE DATOS
    restart: always

  consumer:
    container_name: consumer_app
    build: "consumer/"
    environment:
      - QUEUENAME=demoq
    networks:
      - app_network
    depends_on:
      - rabbitmq
    volumes:
      - ./persistent-data:/code/app/data  # MISMA PERSISTENCIA
    restart: always

  # NUEVO SERVICIO - API para leer JSON
  reader-api:
    build: ./producer  # Reutilizar la imagen del producer
    ports:
      - "8081:8000"
    volumes:
      - ./persistent-data:/code/app/data
    command: uvicorn reader:app --host 0.0.0.0 --port 8000

networks:
  app_network:
    driver: bridge
